FROM golang:alpine as builder

RUN apk add -U git gcc bind-dev musl-dev

WORKDIR /go-dnsperf

COPY . .
RUN CGO_ENABLED=1 go build

FROM alpine:3.9

COPY --from=builder /go-dnsperf/go-dnsperf /go-dnsperf

ENTRYPOINT ["/go-dnsperf"]
